apiVersion: v1
kind: Service
metadata:
 name: fleetman-webapp
spec:
 selector:
  app: webapp
 ports:
 - name: http
   port: 8080 #LoadBalancer Port better to use 80
   targetPort: 80  #container Port
 type: LoadBalancer