apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app-rs
  labels:
    app: web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      layer: ui
  template:
    metadata:
     name: webapp-pod
     labels:
      layer: ui
    spec:
     containers:
     - name: webapp
       image: mrsam1234/node-js:v1
